### PR TITLE
Add support for estimateGas

### PR DESCRIPTION
**Pull request by area**
Add support for the `estimateGas` RPC call (and tests for it). I've taken a lot of 'inspiration' from the implementation of `call` (i.e. copy and paste). I'm not too happy about it, but thought I'd do it this way and get input before assuming that a refactor was desirable.

I've based this branch off of the `rawTx` branch, as I assume that's going to be merged in short order. I'll rebase this branch once it gets merged in.

### CODE REVIEW

**Comment by tcoulter** [comment]
@area You're becoming one of my favorite contributors. Thanks! Will take a look.

Also, you're right about the rawTx branch. Sounds good.

**Comment by tcoulter** [comment]
I've created a new branch called `area-estimateGas` with these changes. I've added a commit which simply adds `eth_estimateGas` to the README.

**Comment by tcoulter** [comment]
FYI: rawTx branch is merged.

**Comment by area** [comment]
What would you like me to do with this PR now, then? It seems like the simplest thing is for you to just merge in the area-estimateGas branch?

**Comment by tcoulter** [comment]
I'll take care of it today hopefully. Thanks!

**Comment by tcoulter** [comment]
Merged! There was actually a big shakeup in the code here. estimateGas support has been moved to the web3-provider-engine; eth_call support is there as well.

**Comment by tcoulter** [comment]
Thanks again!

**Pull request merged**
